/* Index used for searching */
/*
   Fields used:
     url, name, type, filename, authors, routine name, comments, parameters,
     categories, and attributes
*/
title = "Documentation for /Users/penton/JWST/pro/";
subtitle = "Generated by IDLdoc";
libdata = new Array();
libdataItem = 0;



libdata[libdataItem++] = new Array("./get_jwst_dir.html", "get_jwst_dir.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "get_jwst_dir.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./get_jwst_dir.html#get_jwst_dir", "get_jwst_dir", 'routine in <a href="./get_jwst_dir.html">get_jwst_dir.pro</a>', "get_jwst_dir.pro", "", "get_jwst_dir", "", "txtpngvfilessiafdatniriss", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./get_visit42_angle.html", "get_visit42_angle.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "get_visit42_angle.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./get_visit42_angle.html#get_visit42_angle", "get_visit42_angle", 'routine in <a href="./get_visit42_angle.html">get_visit42_angle.pro</a>', "get_visit42_angle.pro", "", "get_visit42_angle", "", "", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_dither_to_sam.html", "jwst_dither_to_sam.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_dither_to_sam.pro", "", "", " Given a DITHER for a particular Science Instrument (SI) and APERTURE NAME (APERNAME), convert this to a SAM   Small Angle Maneuvers (SAMs) are always in [V2,V3] arcseconds in the FGS frame.  This can be either FGS1 (Guider1) or FGS2 (Guider2).   :Author:     Steven V. Penton   Keywords: 	dither: in, required, type=double array (2)      A dither tuple in the arcseconds in the reference frame of the given SI and APERNAME  	si: in, required, string  		The Science Instrument, must be one of                 NRC | Nircam                 NRS | Nirspec                 NIR | Niriss                 MIR | MIRI                 FGS 		NOT case-sensitive  	apername: in, required, string 			Must be a valid Aperture Name for the SI in question     verbose : in, optional, type=boolean        if set, print informational messages     debug : in, optional, type=boolean        if set, output debugging information     redo : in, optional, type=boolean, default = NO (0)        if set, re-create the siaf file for the given SI     out_apername : in, optional, type=string        if set, overrides the default of 'FGS1_FULL_OSS'     out_si : in, optional, type=string        if set, overrides the default of 'FGS'  ", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_dither_to_sam.html#jwst_dither_to_sam", "jwst_dither_to_sam", 'routine in <a href="./jwst_dither_to_sam.html">jwst_dither_to_sam.pro</a>', "jwst_dither_to_sam.pro", "", "jwst_dither_to_sam", "", "verbosedebugredoout_apernameout_sidithersiapername", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_get_dir.html", "jwst_get_dir.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_get_dir.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_get_dir.html#jwst_get_dir", "jwst_get_dir", 'routine in <a href="./jwst_get_dir.html">jwst_get_dir.pro</a>', "jwst_get_dir.pro", "    Steven V. Penton   ", "jwst_get_dir", " Set the directory base for SVP's JWST IDL code   ", "txt       if set, add  txt/  to the end of the output directory  png       if set, add  png/  to the end of the output directory  vfiles       if set, add  vfiles/  to the end of the output directory  siaf       if set, set directory to base+'SIAF/'  dat       if set, add  dat/  to the end of the output directory  fgs       if set, set directory to base+'FGS/'  niriss       if set, set directory to base+'NIRISS/'  nircam       if set, set directory to base+'NIRCAM/'  miri       if set, set directory to base+'MIRI/'  nirspec       if set, set directory to base+'NIRSPEC/'  verbose       if set, print informational messages  debug       if set, output debugging information  ", "          -1", "    None       For example:     IDL&gt; jwst_base_dir=jwst_get_dir(verbose=verbose,nircam=nircam)       IDL 8+   ");
  
  

libdata[libdataItem++] = new Array("./jwst_get_si_info_from_siaf.html", "jwst_get_si_info_from_siaf.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_get_si_info_from_siaf.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_get_si_info_from_siaf.html#jwst_get_si_info_from_siaf", "jwst_get_si_info_from_siaf", 'routine in <a href="./jwst_get_si_info_from_siaf.html">jwst_get_si_info_from_siaf.pro</a>', "jwst_get_si_info_from_siaf.pro", "", "jwst_get_si_info_from_siaf", "", "verboseSI", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_get_siaf_info.html", "jwst_get_siaf_info.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_get_siaf_info.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_get_siaf_info.html#get_siaf_info", "get_siaf_info", 'routine in <a href="./jwst_get_siaf_info.html">jwst_get_siaf_info.pro</a>', "jwst_get_siaf_info.pro", "", "get_siaf_info", "", "shdrverbosepidrootname", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_get_visit42_dithers.html", "jwst_get_visit42_dithers.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_get_visit42_dithers.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_get_visit42_dithers.html#jwst_get_visit42_dithers", "jwst_get_visit42_dithers", 'routine in <a href="./jwst_get_visit42_dithers.html">jwst_get_visit42_dithers.pro</a>', "jwst_get_visit42_dithers.pro", "", "jwst_get_visit42_dithers", "", "verbosedo_plot", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_nircam_dithertest.html", "jwst_nircam_dithertest.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_nircam_dithertest.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_nircam_dithertest.html#jwst_nircam_dithertest", "jwst_nircam_dithertest", 'routine in <a href="./jwst_nircam_dithertest.html">jwst_nircam_dithertest.pro</a>', "jwst_nircam_dithertest.pro", "", "jwst_nircam_dithertest", "", "verbosedo_plot", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_nircam_verify_dithers.html", "jwst_nircam_verify_dithers.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_nircam_verify_dithers.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_nircam_verify_dithers.html#jwst_nircam_verify_dithers", "jwst_nircam_verify_dithers", 'routine in <a href="./jwst_nircam_verify_dithers.html">jwst_nircam_verify_dithers.pro</a>', "jwst_nircam_verify_dithers.pro", "", "jwst_nircam_verify_dithers", "", "verbosedebugcriteriaoutfileoutdir", "          -1", "");
  
  libdata[libdataItem++] = new Array("./jwst_nircam_verify_dithers.html#no_sams", "no_sams", 'routine in <a href="./jwst_nircam_verify_dithers.html">jwst_nircam_verify_dithers.pro</a>', "jwst_nircam_verify_dithers.pro", "", "no_sams", "", "", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_nrc_def_ta.html", "jwst_nrc_def_ta.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_nrc_def_ta.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_nrc_def_ta.html#jwst_nrc_def_ta", "jwst_nrc_def_ta", 'routine in <a href="./jwst_nrc_def_ta.html">jwst_nrc_def_ta.pro</a>', "jwst_nrc_def_ta.pro", "", "jwst_nrc_def_ta", "", "verbosedebug", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_read_si_siaf.html", "jwst_read_si_siaf.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_read_si_siaf.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_read_si_siaf.html#jwst_get_siaf_allsi", "jwst_get_siaf_allsi", 'routine in <a href="./jwst_read_si_siaf.html">jwst_read_si_siaf.pro</a>', "jwst_read_si_siaf.pro", "", "jwst_get_siaf_allsi", "", "redoverbosedebug", "          -1", "");
  
  libdata[libdataItem++] = new Array("./jwst_read_si_siaf.html#jwst_read_si_siaf", "jwst_read_si_siaf", 'routine in <a href="./jwst_read_si_siaf.html">jwst_read_si_siaf.pro</a>', "jwst_read_si_siaf.pro", "", "jwst_read_si_siaf", "", "redoverbosedebugSI", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_rot1.html", "jwst_rot1.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_rot1.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_rot1.html#jwst_rot1", "jwst_rot1", 'routine in <a href="./jwst_rot1.html">jwst_rot1.pro</a>', "jwst_rot1.pro", "", "jwst_rot1", "", "in_arcsecin_degreein_radianang", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_rot2.html", "jwst_rot2.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_rot2.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_rot2.html#jwst_rot2", "jwst_rot2", 'routine in <a href="./jwst_rot2.html">jwst_rot2.pro</a>', "jwst_rot2.pro", "", "jwst_rot2", "", "in_arcsecin_degreein_radianang", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_rot3.html", "jwst_rot3.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_rot3.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_rot3.html#jwst_rot3", "jwst_rot3", 'routine in <a href="./jwst_rot3.html">jwst_rot3.pro</a>', "jwst_rot3.pro", "", "jwst_rot3", "", "in_arcsecin_degreein_radianang", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_si_det_to_sci.html", "jwst_si_det_to_sci.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_si_det_to_sci.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_si_det_to_sci.html#jwst_si_det_to_sci", "jwst_si_det_to_sci", 'routine in <a href="./jwst_si_det_to_sci.html">jwst_si_det_to_sci.pro</a>', "jwst_si_det_to_sci.pro", "", "jwst_si_det_to_sci", "", "verbosedebugXDetRefYDetRefXSciRefYSciRefDetSciParityxydetsiapername", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_si_sci_to_det.html", "jwst_si_sci_to_det.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_si_sci_to_det.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_si_sci_to_det.html#jwst_si_sci_to_det", "jwst_si_sci_to_det", 'routine in <a href="./jwst_si_sci_to_det.html">jwst_si_sci_to_det.pro</a>', "jwst_si_sci_to_det.pro", "", "jwst_si_sci_to_det", "", "verbosedebugXSciRefYSciRefXDetRefYDetRefDetSciParityxyScisiapername", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_si_sci_to_idl.html", "jwst_si_sci_to_idl.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_si_sci_to_idl.pro", "", "", " Convert from SI Science (SCI) coordinates to Ideal (Idl) coordinates     :Author:     Steven V. Penton   Keywords: 	xySci: in, required, type=double array (2)      A xySci tuple in the pixels in the reference frame of the given SI and APERNAME  	si: in, required, string  		The Science Instrument, must be one of                 NRC | Nircam                 NRS | Nirspec                 NIR | Niriss                 MIR | MIRI                 FGS 		NOT case-sensitive 	xyIdl: out, structure 		contains the output structure  	apername: in, required, string 			Must be a valid Aperture Name for the SI in question     verbose : in, optional, type=boolean        if set, print informational messages     debug : in, optional, type=boolean        if set, output debugging information     redo : in, optional, type=boolean, default = NO (0)        if set, re-create the siaf file for the given SI     out_apername : in, optional, type=string        if set, overrides the default of 'FGS1_FULL_OSS'     out_si : in, optional, type=string        if set, overrides the default of 'FGS'  ", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_si_sci_to_idl.html#test_si_sti", "test_si_sti", 'routine in <a href="./jwst_si_sci_to_idl.html">jwst_si_sci_to_idl.pro</a>', "jwst_si_sci_to_idl.pro", "", "test_si_sti", "", "verbosedebugsiapername", "          -1", "");
  
  libdata[libdataItem++] = new Array("./jwst_si_sci_to_idl.html#jwst_si_sci_to_idl", "jwst_si_sci_to_idl", 'routine in <a href="./jwst_si_sci_to_idl.html">jwst_si_sci_to_idl.pro</a>', "jwst_si_sci_to_idl.pro", "", "jwst_si_sci_to_idl", "", "verbosedebugXSciRefYSciRefXDetRefYDetRefIdlSciParityxyScisiapername", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_si_v23_to_xyidl.html", "jwst_si_v23_to_xyidl.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_si_v23_to_xyidl.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_si_v23_to_xyidl.html#jwst_si_v23_to_xyidl", "jwst_si_v23_to_xyidl", 'routine in <a href="./jwst_si_v23_to_xyidl.html">jwst_si_v23_to_xyidl.pro</a>', "jwst_si_v23_to_xyidl.pro", "", "jwst_si_v23_to_xyidl", "", "verbosedebugv2refv3refvIdlparityv23siapername", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_si_xyidl_to_v23.html", "jwst_si_xyidl_to_v23.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_si_xyidl_to_v23.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_si_xyidl_to_v23.html#jwst_si_xyidl_to_v23", "jwst_si_xyidl_to_v23", 'routine in <a href="./jwst_si_xyidl_to_v23.html">jwst_si_xyidl_to_v23.pro</a>', "jwst_si_xyidl_to_v23.pro", "", "jwst_si_xyidl_to_v23", "", "verbosedebugv2refv3refvIdlparityxyidlsiapername", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_t_to_a.html", "jwst_t_to_a.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_t_to_a.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_t_to_a.html#jwst_t_to_a", "jwst_t_to_a", 'routine in <a href="./jwst_t_to_a.html">jwst_t_to_a.pro</a>', "jwst_t_to_a.pro", "", "jwst_t_to_a", "", "verbosev2av3av2tv3t", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_test_t_to_a.html", "jwst_test_t_to_a.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_test_t_to_a.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_test_t_to_a.html#jwst_test_t_to_a", "jwst_test_t_to_a", 'routine in <a href="./jwst_test_t_to_a.html">jwst_test_t_to_a.pro</a>', "jwst_test_t_to_a.pro", "", "jwst_test_t_to_a", "", "siverbose", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_unit_to_v23a.html", "jwst_unit_to_v23a.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_unit_to_v23a.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_unit_to_v23a.html#jwst_unit_to_v23a", "jwst_unit_to_v23a", 'routine in <a href="./jwst_unit_to_v23a.html">jwst_unit_to_v23a.pro</a>', "jwst_unit_to_v23a.pro", "", "jwst_unit_to_v23a", "", "uv", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_unit_to_v23r.html", "jwst_unit_to_v23r.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_unit_to_v23r.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_unit_to_v23r.html#jwst_unit_to_v23r", "jwst_unit_to_v23r", 'routine in <a href="./jwst_unit_to_v23r.html">jwst_unit_to_v23r.pro</a>', "jwst_unit_to_v23r.pro", "", "jwst_unit_to_v23r", "", "uv", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_v23_to_SI_idl.html", "jwst_v23_to_SI_idl.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_v23_to_SI_idl.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_v23_to_SI_idl.html#jwst_v23_to_SI_idl", "jwst_v23_to_SI_idl", 'routine in <a href="./jwst_v23_to_SI_idl.html">jwst_v23_to_SI_idl.pro</a>', "jwst_v23_to_SI_idl.pro", "", "jwst_v23_to_SI_idl", "", "SIAPERTUREoutv2refv3refv23", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./jwst_v23_to_unit.html", "jwst_v23_to_unit.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "jwst_v23_to_unit.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./jwst_v23_to_unit.html#jwst_v23_to_unit", "jwst_v23_to_unit", 'routine in <a href="./jwst_v23_to_unit.html">jwst_v23_to_unit.pro</a>', "jwst_v23_to_unit.pro", "", "jwst_v23_to_unit", "", "v2av3a", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./make_jwst.html", "make_jwst.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "make_jwst.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./make_jwst.html#make_jwst", "make_jwst", 'routine in <a href="./make_jwst.html">make_jwst.pro</a>', "make_jwst.pro", "", "make_jwst", "", "", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./nircam_dither_test.html", "nircam_dither_test.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "nircam_dither_test.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./nircam_dither_test.html#nircam_dither_test", "nircam_dither_test", 'routine in <a href="./nircam_dither_test.html">nircam_dither_test.pro</a>', "nircam_dither_test.pro", "", "nircam_dither_test", "", "redoverbosedebug", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./plot_ns_refstars.html", "plot_ns_refstars.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "plot_ns_refstars.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./plot_ns_refstars.html#plot_ns_refstars", "plot_ns_refstars", 'routine in <a href="./plot_ns_refstars.html">plot_ns_refstars.pro</a>', "plot_ns_refstars.pro", "", "plot_ns_refstars", "", "", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./read_fgs_siaf.html", "read_fgs_siaf.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "read_fgs_siaf.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./read_fgs_siaf.html#read_FGS_siaf", "read_FGS_siaf", 'routine in <a href="./read_fgs_siaf.html">read_fgs_siaf.pro</a>', "read_fgs_siaf.pro", "", "read_FGS_siaf", "", "redoverbose", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./read_miri_siaf.html", "read_miri_siaf.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "read_miri_siaf.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./read_miri_siaf.html#read_MIRI_siaf", "read_MIRI_siaf", 'routine in <a href="./read_miri_siaf.html">read_miri_siaf.pro</a>', "read_miri_siaf.pro", "", "read_MIRI_siaf", "", "redoverbose", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./read_niriss_guider.html", "read_niriss_guider.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "read_niriss_guider.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./read_niriss_guider.html#read_niriss_guider", "read_niriss_guider", 'routine in <a href="./read_niriss_guider.html">read_niriss_guider.pro</a>', "read_niriss_guider.pro", "", "read_niriss_guider", "", "visit42", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./read_niriss_siaf.html", "read_niriss_siaf.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "read_niriss_siaf.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./read_niriss_siaf.html#read_niriss_siaf", "read_niriss_siaf", 'routine in <a href="./read_niriss_siaf.html">read_niriss_siaf.pro</a>', "read_niriss_siaf.pro", "", "read_niriss_siaf", "", "redoverbose", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./read_niriss_siaf_mini.html", "read_niriss_siaf_mini.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "read_niriss_siaf_mini.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./read_niriss_siaf_mini.html#read_niriss_siaf_mini", "read_niriss_siaf_mini", 'routine in <a href="./read_niriss_siaf_mini.html">read_niriss_siaf_mini.pro</a>', "read_niriss_siaf_mini.pro", "", "read_niriss_siaf_mini", "", "", "          -1", "");
  
  

libdata[libdataItem++] = new Array("./svp_jwsw_template.html", "svp_jwsw_template.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "svp_jwsw_template.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./svp_jwsw_template.html#SVPcode", "SVPcode", 'routine in <a href="./svp_jwsw_template.html">svp_jwsw_template.pro</a>', "svp_jwsw_template.pro", "    Steven V. Penton   ", "SVPcode", " Generic template for SVPcode procedure. Insert the purpose of the routine here..   ", "verbose       if set, print informational messages  debug       if set, output debugging information  ", "          -1", "    None       IDL 8+   ");
  
  

libdata[libdataItem++] = new Array("./test_visit24.html", "test_visit24.pro", '.pro file in <a href="./dir-overview.html">./ directory</a>', "test_visit24.pro", "", "", "", "", "          -1", "");
  
  
  libdata[libdataItem++] = new Array("./test_visit24.html#test_visit24", "test_visit24", 'routine in <a href="./test_visit24.html">test_visit24.pro</a>', "test_visit24.pro", "", "test_visit24", "", "", "          -1", "");
  
  

